- name: INSTALL BASE PACKAGES
  hosts: all
  become: True

  tasks:
    - name: Install General Packages
      ansible.builtin.apt:
        name:
          - vim
          - pv
          - tree
          - apt-transport-https
          - ca-certificates
          - curl
          - wget
          - gnupg
          - gnupg-agent
          - lsb-release
          - vim
          - build-essential
          - make
          - dkms
          - git
          - ssh
          - rsync
          - jq
          - python3-debian
        state: latest

    - name: Compress and Uncompress
      ansible.builtin.apt:
        name:
          - bzip2
          - zip
          - unzip
          - xz-utils
        state: latest

    - name: Extra Tools
      ansible.builtin.apt:
        name:
          - whois
          - htop
        state: latest

    - name: Kubernetes repository
      ansible.builtin.deb822_repository:
        name: kubernetes
        types: deb
        uris: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/
        suites: /
        signed_by: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key
        enabled: true

  vars:
    ansible_user: pi
    ansible_private_key_file: ~/.ssh/rpi-ssh
    ansible_port: 22
    k8s_version: 1.36

# Default Raspbian User: pi
# Default Raspbian Password: raspbian
# Default Raspbian Config: sudoers.d NOPASSWD