- name: INSTALL PACKAGES BASE
  hosts: all
  become: True

  tasks:
    - name: Install General Packages
      apt:
        name:
          - vim
          - pv
          - tree
          - apt-transport-https
          - ca-certificates
          - curl
          - wget
          - gnupg
          - gnupg-agent
          - lsb-release
          - vim
          - build-essential
          - make
          - dkms
          - git
          - ssh
          - rsync
          - jq
        state: latest

    - name: Compress and Uncompress
      apt:
        name:
          - bzip2
          - zip
          - unzip
          - xz-utils
        state: latest

    - name: Extra Tools
      apt:
        name:
          - whois
          - htop
        state: latest

  vars:
    ansible_user: pi
    ansible_private_key_file: ~/.ssh/rpi-ssh
    ansible_port: 22

# Default Raspbian User: pi
# Default Raspbian Password: raspbian
# Default Raspbian Config: sudoers.d NOPASSWD