- name: RPI POWER OFF
  hosts: all
  become: True

  tasks:
    - name: Power Off Raspberry Pi
      community.general.shutdown:
        msg: "Powering off the Raspberry Pi"
        delay: 0

  vars:
    ansible_user: pi
    ansible_private_key_file: ~/.ssh/rpi-ssh
    ansible_port: 22

# Default Raspbian User: pi
# Default Raspbian Password: raspbian
# Default Raspbian Config: sudoers.d NOPASSWD